<a href="https://colab.research.google.com/github/parshav42/50_ML_models/blob/main/smenew.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [6]:
tensor_A = torch.tensor([[1,2,3],[4,5,6],[7,8,9]],dtype= torch.float32)

tensor_A.ndim

2

In [8]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=3, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 3])

Output:
tensor([[0.7245, 0.7740, 1.6579, 0.8366, 1.1836, 1.4476],
        [3.0806, 2.3351, 3.3587, 1.3955, 3.5330, 2.7943],
        [5.4366, 3.8962, 5.0596, 1.9545, 5.8824, 4.1410]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [14]:
tensor_A.view(3,3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [15]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [17]:
te = torch.rand(7,7)
te.shape

torch.Size([7, 7])

In [19]:
te2 = torch.rand(1,7)
te2.shape

torch.Size([1, 7])

In [21]:
te @ te2.T

tensor([[1.2454],
        [1.8299],
        [1.6127],
        [1.2702],
        [1.0140],
        [1.5136],
        [1.1810]])

In [29]:
torch.manual_seed(42)

a = torch.rand(2,3)
b = torch.rand(3,2)

a @ b

tensor([[0.6185, 0.6298],
        [1.0856, 0.4059]])

In [31]:
device = torch.device ('cude' if torch.cuda.is_available() else 'cpu')
device

device(type='cpu')

In [ ]:
torch.manual_seed(42)



